print("Welcome")
file=open("biodata.txt","w")
file.write("SHAKTI PRASAD RAM ")
file.write("SATYA SOBHAN RAM ")
file.write("2022 ")
file.close()
file=open("biodata.txt","r")
print(file.read())
file.close()
file=open("biodata.txt","a")
file.write("MOTHERS NAME : MINATI RAM")
file.close()
file=open("biodata.txt","r")
print(file.read())
print("THANK YOU")
